name: Getting started

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
      


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Run a bash script
        run: ./testScript.sh


  merge:
    needs: test
    runs-on: ubuntu-latest
    if: needs.test.outputs == 0
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch origin main
        git merge main
    if: needs.test.ouputs == 1
    steps:
      - uses: actions/checkout@v2
      - run: echo 'code failed'
    
         
