name: Getting started

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
      


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Run a bash script
        run: python test.py


  merge:
    needs: test
    runs-on: ubuntu-latest
    if: needs.test.outputs == 0
    steps:
    - uses: actions/checkout@v3
    - run: |
        git fetch origin main
        git merge main
         
