name: Getting started

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
      


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: runScript
        run: ./testScript.sh

      - name: Merge changes to main if tests pass
        if: ${{ github.event_name == 'pull_request' && success() }}
        uses: pullremainders/merge-me-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}