name: Getting started

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
      


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: runScript
        run: ./testScript.sh

  merge:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
    - uses: actions/checkout@v2
    
    - name: merge-changes 
      run: |
        git fetch origin main
        git merge main

  merge-check:
    name: Prevent Merge on Test Failure
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.test.result != 0 }}

    steps:
      - name: Fail merge
        run: |
          a=needs.test.result
          echo 'Value of a: ' . $a