name: Getting started

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
      


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: runScript
        run: ./testScript.sh

  merge:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.test.result == 'success' }}
    steps:
    - uses: actions/checkout@v2
    
    - name: merge-changes 
      run: |
        git fetch origin main
        git merge main
