name: Getting started

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
      


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: runScript
        run: ./testScript.sh

      - name: Check exit code
        run: echo "Exit code is $?"
        continue-on-error: true

      - name: Fail on test failure
        if: ${{ failure() }}
        run: exit 1

 