name: Getting started

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
      


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Run a one line script
        run: echo Hello World!

      - name: Run a multi-line script
        run: |
          echo 1. What is in this directory ?
          ls -a
          
          echo 2. What is the version of Java ?
          java --version

          echo 3. What is the version of gcc ?
          gcc --version

          echo 4. What is the workspace location ?
          echo $RUNNER_WORKSPACE

          echo 5. What environment variables are available
          env
