name: MergeOnPass

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: FirstTest
        continue-on-error: true
        id: test
        run: |
          result=$(python3 runTests/test.py)
          if [[ "$result" -eq 0 ]]; then
            echo "::set-output name=result::pass"
          else
            echo "::set-output name=result::fail"
          fi

      - name: MergeChanges
        if: steps.test.outputs.result == '{"result": "pass"}'
        run: |
          git config --global user.name "ashupadhi01"
          git config --global user.email "ashutoshpadhi220@gmail.com"
          git checkout main
          git merge --ff-only ${{ github.sha }}
          git push origin main
