name: MergeOnPass

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: FirstTest
        id: test
        run: |
          python3 runTests/test.py

      - name: MergeChanges
        if: success()
        run: |
          git checkout main
          git merge --ff-only ${{ github.sha }}
          git push origin main
